### ISSUE TITLE
Header problems with CORS

### ISSUE THREAD

**Issue by mapu77** [mapu77/hacker-news#6]
Swagger requires to work with CORS due to its cross-origin calls.
They said to add this code to our header's response:
`Access-Control-Allow-Origin: editor.swagger.io`
`Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept`

We need a way not to replicate this in our code and have a function that adds this on every response.

**Comment by ghost** [comment]
In order to solve this, we included this method in our "application_controller.rb":
```
  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = '*'
    headers['Access-Control-Max-Age'] = "1728000"
  end
```
 ... and then we must include a "after_action" of this previous method at the top of every other controller
